### ISSUE TITLE
在 Vite 下使用异常

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/js-sdk#5]
```
[vite] Internal server error: Failed to resolve entry for package "@halo-dev/admin-api". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
  File: /Users/ryanwang/Workspace/github/halo-dev/halo-admin-next/src/utils/api-client.ts
      at resolvePackageEntry (/Users/ryanwang/Workspace/github/halo-dev/halo-admin-next/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:32628:15)
      at tryNodeResolve (/Users/ryanwang/Workspace/github/halo-dev/halo-admin-next/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:32447:11)
      at Context.resolveId (/Users/ryanwang/Workspace/github/halo-dev/halo-admin-next/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:32330:28)
      at Object.resolveId (/Users/ryanwang/Workspace/github/halo-dev/halo-admin-next/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:44739:55)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)
      at async TransformContext.resolve (/Users/ryanwang/Workspace/github/halo-dev/halo-admin-next/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:44541:23)
      at async normalizeUrl (/Users/ryanwang/Workspace/github/halo-dev/halo-admin-next/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:70738:34)
      at async TransformContext.transform (/Users/ryanwang/Workspace/github/halo-dev/halo-admin-next/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:70873:57)
      at async Object.transform (/Users/ryanwang/Workspace/github/halo-dev/halo-admin-next/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:44796:30)
      at async transformRequest (/Users/ryanwang/Workspace/github/halo-dev/halo-admin-next/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:60267:29) (x5)
```

**Comment by guqing** [comment]
好的 会尽快修复
